import type { Chemical } from "./schemas/chemical";

// All 118 elements with reactivity and stability ratings
export const ALL_ELEMENTS: Chemical[] = [
  // ── Period 1 ──
  { id: "hydrogen", name: "Hydrogen", formula: "H₂", color: "hsl(200, 40%, 85%)", state: "gas", category: "nonmetal", reactivity: 6, stability: 5 },
  { id: "helium", name: "Helium", formula: "He", color: "hsl(50, 60%, 80%)", state: "gas", category: "noble-gas", reactivity: 0, stability: 10 },

  // ── Period 2 ──
  { id: "lithium", name: "Lithium", formula: "Li", color: "hsl(220, 10%, 80%)", state: "solid", category: "metal", subcategory: "alkali-metal", reactivity: 7, stability: 4 },
  { id: "beryllium", name: "Beryllium", formula: "Be", color: "hsl(160, 10%, 75%)", state: "solid", category: "metal", subcategory: "alkaline-earth", reactivity: 3, stability: 7 },
  { id: "boron", name: "Boron", formula: "B", color: "hsl(30, 30%, 45%)", state: "solid", category: "nonmetal", subcategory: "metalloid", reactivity: 2, stability: 8 },
  { id: "carbon", name: "Carbon", formula: "C", color: "hsl(0, 0%, 20%)", state: "solid", category: "nonmetal", reactivity: 4, stability: 8 },
  { id: "nitrogen", name: "Nitrogen", formula: "N₂", color: "hsl(210, 30%, 75%)", state: "gas", category: "nonmetal", reactivity: 2, stability: 9 },
  { id: "oxygen", name: "Oxygen", formula: "O₂", color: "hsl(200, 60%, 70%)", state: "gas", category: "nonmetal", reactivity: 7, stability: 6 },
  { id: "fluorine", name: "Fluorine", formula: "F₂", color: "hsl(55, 80%, 70%)", state: "gas", category: "nonmetal", subcategory: "halogen", reactivity: 10, stability: 3 },
  { id: "neon", name: "Neon", formula: "Ne", color: "hsl(0, 80%, 60%)", state: "gas", category: "noble-gas", reactivity: 0, stability: 10 },

  // ── Period 3 ──
  { id: "sodium", name: "Sodium", formula: "Na", color: "hsl(220, 10%, 75%)", state: "solid", category: "metal", subcategory: "alkali-metal", reactivity: 8, stability: 3 },
  { id: "magnesium", name: "Magnesium", formula: "Mg", color: "hsl(220, 8%, 82%)", state: "solid", category: "metal", subcategory: "alkaline-earth", reactivity: 6, stability: 5 },
  { id: "aluminium", name: "Aluminium", formula: "Al", color: "hsl(210, 8%, 78%)", state: "solid", category: "metal", subcategory: "post-transition", reactivity: 5, stability: 6 },
  { id: "silicon", name: "Silicon", formula: "Si", color: "hsl(220, 5%, 55%)", state: "solid", category: "nonmetal", subcategory: "metalloid", reactivity: 3, stability: 8 },
  { id: "phosphorus", name: "Phosphorus", formula: "P", color: "hsl(0, 0%, 90%)", state: "solid", category: "nonmetal", reactivity: 5, stability: 5 },
  { id: "sulfur", name: "Sulfur", formula: "S", color: "hsl(55, 85%, 55%)", state: "solid", category: "nonmetal", reactivity: 5, stability: 7 },
  { id: "chlorine", name: "Chlorine", formula: "Cl₂", color: "hsl(120, 50%, 55%)", state: "gas", category: "nonmetal", subcategory: "halogen", reactivity: 8, stability: 5 },
  { id: "argon", name: "Argon", formula: "Ar", color: "hsl(270, 50%, 70%)", state: "gas", category: "noble-gas", reactivity: 0, stability: 10 },

  // ── Period 4 ──
  { id: "potassium", name: "Potassium", formula: "K", color: "hsl(220, 10%, 70%)", state: "solid", category: "metal", subcategory: "alkali-metal", reactivity: 9, stability: 2 },
  { id: "calcium", name: "Calcium", formula: "Ca", color: "hsl(40, 10%, 85%)", state: "solid", category: "metal", subcategory: "alkaline-earth", reactivity: 7, stability: 4 },
  { id: "scandium", name: "Scandium", formula: "Sc", color: "hsl(200, 10%, 70%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 7 },
  { id: "titanium", name: "Titanium", formula: "Ti", color: "hsl(210, 12%, 65%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 8 },
  { id: "vanadium", name: "Vanadium", formula: "V", color: "hsl(210, 10%, 60%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 7 },
  { id: "chromium", name: "Chromium", formula: "Cr", color: "hsl(210, 15%, 55%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 8 },
  { id: "manganese", name: "Manganese", formula: "Mn", color: "hsl(210, 8%, 58%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 4, stability: 6 },
  { id: "iron", name: "Iron", formula: "Fe", color: "hsl(20, 15%, 40%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 5, stability: 5 },
  { id: "cobalt", name: "Cobalt", formula: "Co", color: "hsl(230, 20%, 50%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 4, stability: 6 },
  { id: "nickel", name: "Nickel", formula: "Ni", color: "hsl(200, 8%, 62%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 7 },
  { id: "copper", name: "Copper", formula: "Cu", color: "hsl(25, 70%, 50%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 8 },
  { id: "zinc", name: "Zinc", formula: "Zn", color: "hsl(210, 5%, 65%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 5, stability: 6 },
  { id: "gallium", name: "Gallium", formula: "Ga", color: "hsl(210, 10%, 70%)", state: "solid", category: "metal", subcategory: "post-transition", reactivity: 3, stability: 7 },
  { id: "germanium", name: "Germanium", formula: "Ge", color: "hsl(210, 5%, 60%)", state: "solid", category: "nonmetal", subcategory: "metalloid", reactivity: 2, stability: 8 },
  { id: "arsenic", name: "Arsenic", formula: "As", color: "hsl(210, 5%, 55%)", state: "solid", category: "nonmetal", subcategory: "metalloid", reactivity: 3, stability: 7 },
  { id: "selenium", name: "Selenium", formula: "Se", color: "hsl(0, 30%, 40%)", state: "solid", category: "nonmetal", reactivity: 4, stability: 7 },
  { id: "bromine", name: "Bromine", formula: "Br₂", color: "hsl(15, 70%, 35%)", state: "liquid", category: "nonmetal", subcategory: "halogen", reactivity: 7, stability: 5 },
  { id: "krypton", name: "Krypton", formula: "Kr", color: "hsl(180, 30%, 70%)", state: "gas", category: "noble-gas", reactivity: 0, stability: 10 },

  // ── Period 5 ──
  { id: "rubidium", name: "Rubidium", formula: "Rb", color: "hsl(220, 10%, 68%)", state: "solid", category: "metal", subcategory: "alkali-metal", reactivity: 9, stability: 2 },
  { id: "strontium", name: "Strontium", formula: "Sr", color: "hsl(40, 10%, 78%)", state: "solid", category: "metal", subcategory: "alkaline-earth", reactivity: 7, stability: 4 },
  { id: "yttrium", name: "Yttrium", formula: "Y", color: "hsl(200, 10%, 72%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 7 },
  { id: "zirconium", name: "Zirconium", formula: "Zr", color: "hsl(210, 10%, 68%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 8 },
  { id: "niobium", name: "Niobium", formula: "Nb", color: "hsl(210, 12%, 60%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 8 },
  { id: "molybdenum", name: "Molybdenum", formula: "Mo", color: "hsl(210, 10%, 58%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 8 },
  { id: "technetium", name: "Technetium", formula: "Tc", color: "hsl(210, 10%, 55%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 4 },
  { id: "ruthenium", name: "Ruthenium", formula: "Ru", color: "hsl(210, 8%, 60%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 8 },
  { id: "rhodium", name: "Rhodium", formula: "Rh", color: "hsl(210, 8%, 65%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 9 },
  { id: "palladium", name: "Palladium", formula: "Pd", color: "hsl(200, 8%, 70%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 8 },
  { id: "silver", name: "Silver", formula: "Ag", color: "hsl(200, 10%, 80%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 8 },
  { id: "cadmium", name: "Cadmium", formula: "Cd", color: "hsl(210, 8%, 65%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 7 },
  { id: "indium", name: "Indium", formula: "In", color: "hsl(210, 10%, 72%)", state: "solid", category: "metal", subcategory: "post-transition", reactivity: 3, stability: 7 },
  { id: "tin", name: "Tin", formula: "Sn", color: "hsl(200, 5%, 72%)", state: "solid", category: "metal", subcategory: "post-transition", reactivity: 3, stability: 7 },
  { id: "antimony", name: "Antimony", formula: "Sb", color: "hsl(210, 8%, 62%)", state: "solid", category: "nonmetal", subcategory: "metalloid", reactivity: 3, stability: 7 },
  { id: "tellurium", name: "Tellurium", formula: "Te", color: "hsl(210, 5%, 58%)", state: "solid", category: "nonmetal", subcategory: "metalloid", reactivity: 3, stability: 7 },
  { id: "iodine", name: "Iodine", formula: "I₂", color: "hsl(270, 40%, 30%)", state: "solid", category: "nonmetal", subcategory: "halogen", reactivity: 5, stability: 6 },
  { id: "xenon", name: "Xenon", formula: "Xe", color: "hsl(220, 40%, 75%)", state: "gas", category: "noble-gas", reactivity: 1, stability: 9 },

  // ── Period 6 ──
  { id: "caesium", name: "Caesium", formula: "Cs", color: "hsl(45, 30%, 60%)", state: "solid", category: "metal", subcategory: "alkali-metal", reactivity: 10, stability: 1 },
  { id: "barium", name: "Barium", formula: "Ba", color: "hsl(40, 10%, 72%)", state: "solid", category: "metal", subcategory: "alkaline-earth", reactivity: 8, stability: 3 },
  { id: "lanthanum", name: "Lanthanum", formula: "La", color: "hsl(200, 10%, 70%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "cerium", name: "Cerium", formula: "Ce", color: "hsl(200, 10%, 68%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "praseodymium", name: "Praseodymium", formula: "Pr", color: "hsl(200, 10%, 66%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "neodymium", name: "Neodymium", formula: "Nd", color: "hsl(200, 10%, 64%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "promethium", name: "Promethium", formula: "Pm", color: "hsl(200, 10%, 62%)", state: "solid", category: "metal", subcategory: "lanthanide", radioactive: true, reactivity: 4, stability: 3 },
  { id: "samarium", name: "Samarium", formula: "Sm", color: "hsl(200, 10%, 60%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "europium", name: "Europium", formula: "Eu", color: "hsl(200, 10%, 58%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 5, stability: 5 },
  { id: "gadolinium", name: "Gadolinium", formula: "Gd", color: "hsl(200, 10%, 66%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "terbium", name: "Terbium", formula: "Tb", color: "hsl(200, 10%, 64%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "dysprosium", name: "Dysprosium", formula: "Dy", color: "hsl(200, 10%, 62%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "holmium", name: "Holmium", formula: "Ho", color: "hsl(200, 10%, 60%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "erbium", name: "Erbium", formula: "Er", color: "hsl(200, 10%, 58%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "thulium", name: "Thulium", formula: "Tm", color: "hsl(200, 10%, 56%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "ytterbium", name: "Ytterbium", formula: "Yb", color: "hsl(200, 10%, 54%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 4, stability: 6 },
  { id: "lutetium", name: "Lutetium", formula: "Lu", color: "hsl(200, 10%, 52%)", state: "solid", category: "metal", subcategory: "lanthanide", reactivity: 3, stability: 7 },
  { id: "hafnium", name: "Hafnium", formula: "Hf", color: "hsl(210, 10%, 62%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 3, stability: 8 },
  { id: "tantalum", name: "Tantalum", formula: "Ta", color: "hsl(210, 10%, 58%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 9 },
  { id: "tungsten", name: "Tungsten", formula: "W", color: "hsl(210, 8%, 55%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 9 },
  { id: "rhenium", name: "Rhenium", formula: "Re", color: "hsl(210, 8%, 58%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 8 },
  { id: "osmium", name: "Osmium", formula: "Os", color: "hsl(220, 10%, 50%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 2, stability: 9 },
  { id: "iridium", name: "Iridium", formula: "Ir", color: "hsl(210, 8%, 62%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 1, stability: 9 },
  { id: "platinum", name: "Platinum", formula: "Pt", color: "hsl(200, 10%, 75%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 1, stability: 9 },
  { id: "gold", name: "Gold", formula: "Au", color: "hsl(45, 80%, 55%)", state: "solid", category: "metal", subcategory: "transition", reactivity: 1, stability: 10 },
  { id: "mercury", name: "Mercury", formula: "Hg", color: "hsl(210, 15%, 70%)", state: "liquid", category: "metal", subcategory: "transition", reactivity: 2, stability: 7 },
  { id: "thallium", name: "Thallium", formula: "Tl", color: "hsl(210, 8%, 65%)", state: "solid", category: "metal", subcategory: "post-transition", reactivity: 3, stability: 6 },
  { id: "lead", name: "Lead", formula: "Pb", color: "hsl(210, 5%, 50%)", state: "solid", category: "metal", subcategory: "post-transition", reactivity: 2, stability: 7 },
  { id: "bismuth", name: "Bismuth", formula: "Bi", color: "hsl(300, 20%, 55%)", state: "solid", category: "metal", subcategory: "post-transition", radioactive: true, reactivity: 2, stability: 7 },
  { id: "polonium", name: "Polonium", formula: "Po", color: "hsl(210, 5%, 55%)", state: "solid", category: "metal", subcategory: "post-transition", radioactive: true, reactivity: 4, stability: 2 },
  { id: "astatine", name: "Astatine", formula: "At", color: "hsl(210, 5%, 40%)", state: "solid", category: "nonmetal", subcategory: "halogen", radioactive: true, reactivity: 6, stability: 1 },
  { id: "radon", name: "Radon", formula: "Rn", color: "hsl(210, 20%, 60%)", state: "gas", category: "noble-gas", radioactive: true, reactivity: 0, stability: 3 },

  // ── Period 7 ──
  { id: "francium", name: "Francium", formula: "Fr", color: "hsl(220, 10%, 65%)", state: "solid", category: "metal", subcategory: "alkali-metal", radioactive: true, reactivity: 10, stability: 1 },
  { id: "radium", name: "Radium", formula: "Ra", color: "hsl(120, 30%, 70%)", state: "solid", category: "metal", subcategory: "alkaline-earth", radioactive: true, reactivity: 8, stability: 2 },
  { id: "actinium", name: "Actinium", formula: "Ac", color: "hsl(200, 10%, 68%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 5, stability: 3 },
  { id: "thorium", name: "Thorium", formula: "Th", color: "hsl(200, 10%, 65%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 4 },
  { id: "protactinium", name: "Protactinium", formula: "Pa", color: "hsl(200, 10%, 62%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 3 },
  { id: "uranium", name: "Uranium", formula: "U", color: "hsl(120, 40%, 45%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 5, stability: 4 },
  { id: "neptunium", name: "Neptunium", formula: "Np", color: "hsl(200, 10%, 58%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 5, stability: 3 },
  { id: "plutonium", name: "Plutonium", formula: "Pu", color: "hsl(200, 10%, 55%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 5, stability: 3 },
  { id: "americium", name: "Americium", formula: "Am", color: "hsl(200, 10%, 52%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 3 },
  { id: "curium", name: "Curium", formula: "Cm", color: "hsl(200, 10%, 50%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 2 },
  { id: "berkelium", name: "Berkelium", formula: "Bk", color: "hsl(200, 10%, 48%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 2 },
  { id: "californium", name: "Californium", formula: "Cf", color: "hsl(200, 10%, 46%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 2 },
  { id: "einsteinium", name: "Einsteinium", formula: "Es", color: "hsl(200, 10%, 44%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 1 },
  { id: "fermium", name: "Fermium", formula: "Fm", color: "hsl(200, 10%, 42%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 1 },
  { id: "mendelevium", name: "Mendelevium", formula: "Md", color: "hsl(200, 10%, 40%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 1 },
  { id: "nobelium", name: "Nobelium", formula: "No", color: "hsl(200, 10%, 38%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 1 },
  { id: "lawrencium", name: "Lawrencium", formula: "Lr", color: "hsl(200, 10%, 36%)", state: "solid", category: "metal", subcategory: "actinide", radioactive: true, reactivity: 4, stability: 1 },
  { id: "rutherfordium", name: "Rutherfordium", formula: "Rf", color: "hsl(210, 10%, 55%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "dubnium", name: "Dubnium", formula: "Db", color: "hsl(210, 10%, 53%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "seaborgium", name: "Seaborgium", formula: "Sg", color: "hsl(210, 10%, 51%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "bohrium", name: "Bohrium", formula: "Bh", color: "hsl(210, 10%, 49%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "hassium", name: "Hassium", formula: "Hs", color: "hsl(210, 10%, 47%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "meitnerium", name: "Meitnerium", formula: "Mt", color: "hsl(210, 10%, 45%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "darmstadtium", name: "Darmstadtium", formula: "Ds", color: "hsl(210, 10%, 43%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "roentgenium", name: "Roentgenium", formula: "Rg", color: "hsl(210, 10%, 41%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "copernicium", name: "Copernicium", formula: "Cn", color: "hsl(210, 10%, 39%)", state: "solid", category: "metal", subcategory: "transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "nihonium", name: "Nihonium", formula: "Nh", color: "hsl(210, 10%, 55%)", state: "solid", category: "metal", subcategory: "post-transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "flerovium", name: "Flerovium", formula: "Fl", color: "hsl(210, 10%, 53%)", state: "solid", category: "metal", subcategory: "post-transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "moscovium", name: "Moscovium", formula: "Mc", color: "hsl(210, 10%, 51%)", state: "solid", category: "metal", subcategory: "post-transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "livermorium", name: "Livermorium", formula: "Lv", color: "hsl(210, 10%, 49%)", state: "solid", category: "metal", subcategory: "post-transition", radioactive: true, reactivity: 3, stability: 1 },
  { id: "tennessine", name: "Tennessine", formula: "Ts", color: "hsl(210, 10%, 47%)", state: "solid", category: "nonmetal", subcategory: "halogen", radioactive: true, reactivity: 3, stability: 1 },
  { id: "oganesson", name: "Oganesson", formula: "Og", color: "hsl(210, 10%, 45%)", state: "gas", category: "noble-gas", radioactive: true, reactivity: 1, stability: 1 },
];

// Compounds - acids, alkalis, salts, indicators, water
export const COMPOUNDS: Chemical[] = [
  // Acids
  { id: "hcl", name: "Hydrochloric Acid", formula: "HCl", color: "hsl(55, 90%, 55%)", state: "liquid", category: "acid", reactivity: 7, stability: 6 },
  { id: "h2so4", name: "Sulfuric Acid", formula: "H₂SO₄", color: "hsl(45, 80%, 50%)", state: "liquid", category: "acid", reactivity: 8, stability: 6 },
  { id: "hno3", name: "Nitric Acid", formula: "HNO₃", color: "hsl(50, 70%, 55%)", state: "liquid", category: "acid", reactivity: 8, stability: 5 },
  { id: "vinegar", name: "Acetic Acid (Vinegar)", formula: "CH₃COOH", color: "hsl(50, 60%, 70%)", state: "liquid", category: "acid", reactivity: 4, stability: 8 },
  { id: "h3po4", name: "Phosphoric Acid", formula: "H₃PO₄", color: "hsl(40, 50%, 60%)", state: "liquid", category: "acid", reactivity: 5, stability: 7 },
  { id: "citric", name: "Citric Acid", formula: "C₆H₈O₇", color: "hsl(55, 70%, 65%)", state: "solid", category: "acid", reactivity: 4, stability: 8 },
  { id: "carbonic", name: "Carbonic Acid", formula: "H₂CO₃", color: "hsl(200, 40%, 70%)", state: "liquid", category: "acid", reactivity: 3, stability: 4 },

  // Alkalis
  { id: "naoh", name: "Sodium Hydroxide", formula: "NaOH", color: "hsl(180, 30%, 70%)", state: "solid", category: "alkali", reactivity: 7, stability: 7 },
  { id: "koh", name: "Potassium Hydroxide", formula: "KOH", color: "hsl(180, 25%, 72%)", state: "solid", category: "alkali", reactivity: 7, stability: 7 },
  { id: "caoh2", name: "Calcium Hydroxide", formula: "Ca(OH)₂", color: "hsl(0, 0%, 88%)", state: "solid", category: "alkali", reactivity: 5, stability: 7 },
  { id: "nh3", name: "Ammonia Solution", formula: "NH₃", color: "hsl(200, 30%, 75%)", state: "liquid", category: "alkali", reactivity: 5, stability: 6 },

  // Water
  { id: "water", name: "Water", formula: "H₂O", color: "hsl(200, 80%, 60%)", state: "liquid", category: "water", reactivity: 3, stability: 9 },

  // Salts
  { id: "baking-soda", name: "Baking Soda", formula: "NaHCO₃", color: "hsl(0, 0%, 92%)", state: "solid", category: "salt", reactivity: 4, stability: 8 },
  { id: "nacl", name: "Table Salt", formula: "NaCl", color: "hsl(0, 0%, 95%)", state: "solid", category: "salt", reactivity: 1, stability: 10 },
  { id: "cuso4", name: "Copper Sulfate", formula: "CuSO₄", color: "hsl(210, 80%, 55%)", state: "solid", category: "salt", reactivity: 4, stability: 7 },
  { id: "agno3", name: "Silver Nitrate", formula: "AgNO₃", color: "hsl(0, 0%, 85%)", state: "solid", category: "salt", reactivity: 5, stability: 6 },
  { id: "pbno3", name: "Lead Nitrate", formula: "Pb(NO₃)₂", color: "hsl(0, 0%, 90%)", state: "solid", category: "salt", reactivity: 4, stability: 6 },
  { id: "fecl3", name: "Iron(III) Chloride", formula: "FeCl₃", color: "hsl(30, 60%, 40%)", state: "solid", category: "salt", reactivity: 5, stability: 6 },
  { id: "ki", name: "Potassium Iodide", formula: "KI", color: "hsl(0, 0%, 90%)", state: "solid", category: "salt", reactivity: 4, stability: 7 },
  { id: "kmno4", name: "Potassium Permanganate", formula: "KMnO₄", color: "hsl(300, 60%, 30%)", state: "solid", category: "salt", reactivity: 7, stability: 5 },

  // Indicators
  { id: "phenolphthalein", name: "Phenolphthalein", formula: "C₂₀H₁₄O₄", color: "hsl(330, 70%, 60%)", state: "liquid", category: "organic", subcategory: "indicator", reactivity: 1, stability: 8 },
  { id: "methyl-orange", name: "Methyl Orange", formula: "C₁₄H₁₄N₃NaO₃S", color: "hsl(30, 90%, 55%)", state: "liquid", category: "organic", subcategory: "indicator", reactivity: 1, stability: 8 },
  { id: "litmus", name: "Litmus Solution", formula: "Litmus", color: "hsl(270, 60%, 50%)", state: "liquid", category: "organic", subcategory: "indicator", reactivity: 1, stability: 8 },
  { id: "universal-indicator", name: "Universal Indicator", formula: "UI", color: "hsl(120, 60%, 45%)", state: "liquid", category: "organic", subcategory: "indicator", reactivity: 1, stability: 7 },
  { id: "bromothymol", name: "Bromothymol Blue", formula: "C₂₇H₂₈Br₂O₅S", color: "hsl(210, 70%, 50%)", state: "liquid", category: "organic", subcategory: "indicator", reactivity: 1, stability: 8 },

  // Hydrogen Peroxide
  { id: "h2o2", name: "Hydrogen Peroxide", formula: "H₂O₂", color: "hsl(200, 50%, 75%)", state: "liquid", category: "water", reactivity: 6, stability: 4 },
];

export const ELEMENT_SUBCATEGORIES: Record<string, string> = {
  "alkali-metal": "Alkali Metals",
  "alkaline-earth": "Alkaline Earth Metals",
  "transition": "Transition Metals",
  "post-transition": "Post-Transition Metals",
  "metalloid": "Metalloids",
  "halogen": "Halogens",
  "lanthanide": "Lanthanides",
  "actinide": "Actinides",
  "indicator": "Indicators",
};
