import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parents[2] / 'Data'
EX_DIR = DATA_DIR / 'extracted_texts'
PARSED = EX_DIR / 'parsed_reactions.json'
OUT = EX_DIR / 'reactions_import.ts'

if not PARSED.exists():
    print('parsed_reactions.json not found')
    raise SystemExit(1)

with open(PARSED, encoding='utf-8') as f:
    parsed = json.load(f)

print(f'Loaded {len(parsed)} parsed reactions')

# Convert to TypeScript Reaction format
reactions_ts = []
for p in parsed:
    reactants = p['reactants']
    products = p['products']
    raw = p['raw_equation']
    
    # Build a basic Reaction object
    # We'll use generic defaults and let the code fill in specific properties
    react_obj = {
        'reactants': reactants,
        'products': products,
        'equation': raw,
        'effect': 'color-change',  # default
        'description': raw,
        'intensity': 'medium',
        'enthalpyChange': -50,  # default exothermic estimate
        'isExothermic': True,
        'temperatureChange': 20,
        'heatReleased': 50,
    }
    reactions_ts.append(react_obj)

# Generate TypeScript code
ts_lines = [
    '// Auto-generated reactions from PDF import - do not edit manually',
    '// Generated by scripts/convert_parsed_reactions.py',
    '',
    'import { Reaction } from "../types";',
    '',
    'export const importedReactions: Reaction[] = [',
]

for i, r in enumerate(reactions_ts):
    ts_lines.append('  {')
    ts_lines.append(f'    reactants: {json.dumps(r["reactants"])},')
    ts_lines.append(f'    products: {json.dumps(r["products"])},')
    ts_lines.append(f'    equation: {json.dumps(r["equation"])},')
    ts_lines.append(f'    effect: "{r["effect"]}",')
    ts_lines.append(f'    description: {json.dumps(r["description"])},')
    ts_lines.append(f'    intensity: "{r["intensity"]}",')
    ts_lines.append(f'    enthalpyChange: {r["enthalpyChange"]},')
    ts_lines.append(f'    isExothermic: {str(r["isExothermic"]).lower()},')
    ts_lines.append(f'    temperatureChange: {r["temperatureChange"]},')
    ts_lines.append(f'    heatReleased: {r["heatReleased"]},')
    ts_lines.append('  },' if i < len(reactions_ts) - 1 else '  },')

ts_lines.append('];')

ts_code = '\n'.join(ts_lines)
OUT.write_text(ts_code, encoding='utf-8')
print(f'Wrote {OUT}')
print(f'Generated {len(reactions_ts)} TypeScript Reaction objects')
